Repository Maserati-Quattroporte/maseraT_pong_game, pull requests merged in 2022-07, with the labels that each got.

#20 [Feat & Modify] A lot. please check message
  frontend/postcss.config.js
  frontend/src/components/Achievement.tsx
  frontend/src/components/BlockList.tsx
  frontend/src/components/ButtonOne.tsx
  frontend/src/components/ChatBox.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/HomeContent.tsx
  frontend/src/components/LoginContent.tsx
  frontend/src/components/MainBox.tsx
  frontend/src/components/PopUpBlock.tsx
  frontend/src/components/PopUpBtnBig.tsx
  frontend/src/components/PopUpCheck.tsx
  frontend/src/components/PopUpNick.tsx
  frontend/src/components/PopUpParent.tsx
  frontend/src/components/PopUpProfile.tsx
  frontend/src/components/PopUpRecord.tsx
  frontend/src/components/PopUpRoomSet.tsx
  frontend/src/components/PopUpSecAuth.tsx
  frontend/src/components/RecordList.tsx
  frontend/src/components/RoomList.tsx
  frontend/src/components/SecAuthContent.tsx
  frontend/src/components/TopNavBar.tsx
  frontend/src/components/UserList.tsx
  frontend/src/components/UserListBox.tsx
  frontend/src/font/UFL.txt
  frontend/src/font/Ubuntu-Bold.ttf
  frontend/src/font/Ubuntu-BoldItalic.ttf
  frontend/src/font/Ubuntu-Italic.ttf
  frontend/src/font/Ubuntu-Light.ttf
  frontend/src/font/Ubuntu-LightItalic.ttf
  frontend/src/font/Ubuntu-Medium.ttf
  frontend/src/font/Ubuntu-MediumItalic.ttf
  frontend/src/font/Ubuntu-Regular.ttf
  frontend/src/index.css
  frontend/src/pages/Home.tsx
  frontend/tailwind.config.js
Labels: enhancement

#21 [Modify] reorganize component directory
  frontend/src/components/Button/ButtonOne.tsx
  frontend/src/components/Button/ButtonTwo.tsx
  frontend/src/components/Button/PopUpBtnBig.tsx
  frontend/src/components/Content/ChatBox.tsx
  frontend/src/components/Content/HomeContent.tsx
  frontend/src/components/Content/LoginContent.tsx
  frontend/src/components/Content/MainBox.tsx
  frontend/src/components/Content/SecAuthContent.tsx
  frontend/src/components/Content/UserListBox.tsx
  frontend/src/components/List/BlockList.tsx
  frontend/src/components/List/RecordList.tsx
  frontend/src/components/List/RoomList.tsx
  frontend/src/components/List/UserList.tsx
  frontend/src/components/PopUp/PopUpBlock.tsx
  frontend/src/components/PopUp/PopUpCheck.tsx
  frontend/src/components/PopUp/PopUpNick.tsx
  frontend/src/components/PopUp/PopUpParent.tsx
  frontend/src/components/PopUp/PopUpProfile.tsx
  frontend/src/components/PopUp/PopUpRecord.tsx
  frontend/src/components/PopUp/PopUpRoomSet.tsx
  frontend/src/components/PopUp/PopUpSecAuth.tsx
Labels: enhancement

#22 [Modify] modify import because reorganized directory
  frontend/src/components/Content/ChatBox.tsx
  frontend/src/components/Content/HomeContent.tsx
  frontend/src/components/Content/LoginContent.tsx
  frontend/src/components/Content/MainBox.tsx
  frontend/src/components/Content/SecAuthContent.tsx
  frontend/src/components/Content/UserListBox.tsx
  frontend/src/components/List/RoomList.tsx
  frontend/src/components/TopNavBar.tsx
  frontend/src/pages/Chat.tsx
  frontend/src/pages/ChatRoom.tsx
  frontend/src/pages/Game.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/LogIn.tsx
  frontend/src/pages/SecondAuth.tsx
Labels: enhancement

#24 [Modify] : Sorry, i forgot.. PopUp also modify import
  frontend/src/components/PopUp/PopUpBlock.tsx
  frontend/src/components/PopUp/PopUpNick.tsx
  frontend/src/components/PopUp/PopUpProfile.tsx
  frontend/src/components/PopUp/PopUpRecord.tsx
  frontend/src/components/PopUp/PopUpRoomSet.tsx
  frontend/src/components/PopUp/PopUpSecAuth.tsx
Labels: enhancement

#25 [Modify] Really Sorry.. modify import img directory
  frontend/src/components/Content/HomeContent.tsx
  frontend/src/components/Content/LoginContent.tsx
  frontend/src/components/Content/SecAuthContent.tsx
  frontend/src/components/List/UserList.tsx
  frontend/src/components/PopUp/PopUpProfile.tsx
Labels: enhancement

#26 Develop
  backend/src/achievement/achievement.entity.ts
  backend/src/achievement/achievement.module.ts
  backend/src/achievement/achievement.repository.ts
  backend/src/achievement/achievement.service.ts
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/guard/jwt-auth.guard.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/block/block.controller.ts
  backend/src/block/block.entity.ts
  backend/src/block/block.module.ts
  backend/src/block/block.repository.ts
  backend/src/block/block.service.ts
  backend/src/block/dto/get-all-block.dto.ts
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/entity/chat-participants.entity.ts
  backend/src/friend/dto/get-all-friends.dto.ts
  backend/src/friend/friend.service.ts
  backend/src/friend/friends.entity.ts
  backend/src/nickname/nickname.module.ts
  backend/src/nickname/nickname.service.ts
  backend/src/record/record.entity.ts
  backend/src/second-auth/second-auth-code.entity.ts
  backend/src/second-auth/second-auth.controller.ts
  backend/src/second-auth/second-auth.module.ts
  backend/src/second-auth/second-auth.repository.ts
  backend/src/second-auth/second-auth.service.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.entity.ts
  backend/src/user/user.module.ts
  backend/src/user/user.repository.ts
  backend/src/user/user.service.ts
Labels: enhancement, help wanted

#34 [Merge]
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/BtnChatMenu.tsx
  frontend/src/components/Button/BtnPopUp.tsx
  frontend/src/components/Content/UserListBox.tsx
  frontend/src/components/List/UserList.tsx
  frontend/src/components/PopUp/PopUpChatMenu.tsx
  frontend/src/components/PopUp/PopUpNick.tsx
  frontend/src/components/PopUp/PopUpProfile.tsx
  frontend/src/components/PopUp/PopUpRoomSet.tsx
  frontend/src/components/PopUp/PopUpSecAuth.tsx
  frontend/src/components/TopNavBar.tsx
  frontend/src/index.tsx
Labels: enhancement

#36 [Merge] : Fix posion of PopUp
  frontend/src/components/Content/UserListBox.tsx
  frontend/src/components/List/UserList.tsx
  frontend/src/components/PopUp/PopUpChatMenu.tsx
Labels: enhancement

#40 [Merge] : add files for connecting back and apply
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/getApi.ts
  frontend/src/components/List/RecordList.tsx
  frontend/src/components/PageLoading.tsx
  frontend/src/components/PageNotFound.tsx
  frontend/src/components/PopUp/PopUpBlock.tsx
  frontend/src/components/PopUp/PopUpProfile.tsx
  frontend/src/components/PopUp/PopUpRecord.tsx
  frontend/src/components/TopNavBar.tsx
  frontend/src/index.tsx
  frontend/src/pages/Game.tsx
  frontend/src/state/getBlock.ts
  frontend/src/state/getRecord.ts
  frontend/src/state/getUserInfo.ts
Labels: enhancement

#43 [Merge] : 머지 안된부분 다시 머지
  frontend/src/pages/Game.tsx
Labels: enhancement

#44 [Modify], [Feat] : add icon, modify
  frontend/src/atom/userInfoAtom.ts
  frontend/src/components/Content/UserListBox.tsx
  frontend/src/img/Admin Icon.svg
  frontend/src/img/Owner Icon.svg
  frontend/src/pages/Chat.tsx
Labels: enhancement

#55 [Merge] : Request Merge!!
  frontend/src/api/deleteApi.ts
  frontend/src/api/postApi.ts
  frontend/src/components/Button/BtnPopUp.tsx
  frontend/src/components/Content/LoginContent.tsx
  frontend/src/components/List/BlockList.tsx
  frontend/src/components/PopUp/PopUpBlock.tsx
  frontend/src/components/PopUp/PopUpChatMenu.tsx
  frontend/src/components/PopUp/PopUpNick.tsx
  frontend/src/components/PopUp/PopUpOtherProfile.tsx
  frontend/src/components/PopUp/PopUpProfile.tsx
  frontend/src/components/PopUp/PopUpRecord.tsx
  frontend/src/state/getAchieve.ts
  frontend/src/state/getBlock.ts
  frontend/src/state/getOtherAchieve.ts
  frontend/src/state/getOtherRecord.ts
  frontend/src/state/getOtherUserInfo.ts
  frontend/src/state/getRecord.ts
  frontend/src/state/getUserInfo.ts
  frontend/src/utils/btnBlockOnC.ts
  frontend/src/utils/btnFriendOnC.ts
  frontend/src/utils/btnUnblockOnC.ts
Labels: enhancement

#56 [MODIFY] : modified PopUpParent
  frontend/public/index.html
  frontend/src/components/PopUp/PopUpParent.tsx
  frontend/src/components/TopNavBar.tsx
Labels: enhancement

#57 [Merge] : Displaying achievement. activate or deactivate second-auth
  frontend/src/api/deleteApi.ts
  frontend/src/api/getApi.ts
  frontend/src/api/postApi.ts
  frontend/src/components/Achievement.tsx
  frontend/src/components/Button/BtnChatMenu.tsx
  frontend/src/components/Button/BtnPopUp.tsx
  frontend/src/components/Button/ButtonOne.tsx
  frontend/src/components/Content/HomeContent.tsx
  frontend/src/components/Content/LoginContent.tsx
  frontend/src/components/Content/SecAuthContent.tsx
  frontend/src/components/PopUp/PopUpBlock.tsx
  frontend/src/components/PopUp/PopUpChatMenu.tsx
  frontend/src/components/PopUp/PopUpCheck.tsx
  frontend/src/components/PopUp/PopUpNick.tsx
  frontend/src/components/PopUp/PopUpOtherProfile.tsx
  frontend/src/components/PopUp/PopUpProfile.tsx
  frontend/src/components/PopUp/PopUpRoomSet.tsx
  frontend/src/components/PopUp/PopUpSecAuth.tsx
  frontend/src/components/TopNavBar.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/LogIn.tsx
  frontend/src/pages/SecondAuth.tsx
  frontend/src/state/getUser.ts
  frontend/src/state/getUserInfo.ts
Labels: enhancement

#52 [Feat] Game socket & API
  backend/src/configs/typeorm.configs.ts
  backend/src/game/dto/game-participant.dto.ts
  backend/src/game/dto/game-room.dto.ts
  backend/src/game/entity/game-participant.entity.ts
  backend/src/game/game.controller.ts
  backend/src/game/game.gateway.ts
  backend/src/game/game.module.ts
  backend/src/game/game.service.ts
  backend/src/game/repository/game-room.repository.ts
Labels: bug, enhancement, help wanted, question

#62 [Refactor] : modify some css
  frontend/src/components/Content/HomeContent.tsx
  frontend/src/components/Content/LoginContent.tsx
  frontend/src/components/Content/SecAuthContent.tsx
  frontend/src/components/PopUp/PopUpSecAuth.tsx
  frontend/src/utils/btnNickOnC.ts
  frontend/src/utils/codeOnChange.ts
Labels: enhancement

#70 [Style] : css for components
  frontend/global.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/component/Footer.tsx
  frontend/src/component/Header.tsx
  frontend/src/component/TopNavBar.tsx
  frontend/src/component/button/Button.tsx
  frontend/src/component/chat-room-list.tsx
  frontend/src/component/chat.tsx
  frontend/src/component/list/all-user.tsx
  frontend/src/component/list/chat-user.tsx
  frontend/src/component/list/freind.tsx
  frontend/src/component/list/user-list.tsx
  frontend/src/img/achievementIcon.svg
  frontend/src/img/admin.svg
  frontend/src/img/circleGreen.svg
  frontend/src/img/circleGrey.svg
  frontend/src/img/circleRed.svg
  frontend/src/img/consecThree.svg
  frontend/src/img/firstLogin.svg
  frontend/src/img/firstLose.svg
  frontend/src/img/firstWin.svg
  frontend/src/img/maserat.png
  frontend/src/img/owner.svg
  frontend/src/img/pong.png
  frontend/src/img/thirdWin.svg
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/popup/PopupControl.tsx
  frontend/src/popup/chat-create-popup.tsx
  frontend/src/popup/chat-password-popup.tsx
  frontend/src/popup/chat-popup.tsx
  frontend/src/popup/chat-room-set-popup.tsx
  frontend/src/popup/profile-popup.tsx
  frontend/src/popup/record.tsx
  frontend/src/popup/second-auth-popup.tsx
  frontend/src/routes/ChatDetail.tsx
  frontend/src/routes/ChatMain.tsx
  frontend/src/routes/Home.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Second-auth.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.json
Labels: enhancement
